### ISSUE TITLE
Need more detail on DMARC entires marked invalid

### ISSUE THREAD

**Issue by alansill** [seanthegeek/mastodon-dmarc-survey#1]
For our server your csv vile shows an evaluation of "invalid" for our DMARC record, but it passes all checks including checking the headers from a message from the server for a received message. Can you provide more detail on what caused your scan to mark this as invalid, please?

mast.hpc.social | A Mastodon instance to support and encourage communication among the High Performance Computing community those in and related fields. | mastodon-admins@hpc.social | admin | 129 | 327 | 4753 | 7688 | Invalid

<img width="705" alt="Screenshot 2023-01-06 at 9 49 20 PM" src="https://user-images.githubusercontent.com/2364484/211129929-877aecdf-4eb9-479d-bfa3-c14455ceef11.png">
<img width="553" alt="Screenshot 2023-01-06 at 9 49 07 PM" src="https://user-images.githubusercontent.com/2364484/211129931-f58c3d63-cb30-4296-a58b-aa5baf2ca6f4.png">

**Comment by alansill** [comment]
Closing this as I was able to find and install the checkdmarc tool to answer the question on my own. Thanks!

**Comment by seanthegeek** [comment]
Glad to hear it. I'm curious, what was your original record and what was checkdmarc complaining about that no one else was?1

**Comment by alansill** [comment]
It was a very trivial error but hard to spot. The google domain tools missed it, as did other mx checkers I had used. 

Instead of an "@" I had a "." in the reporting email address: ... rua=mailto:dmarc-reporting.hpc.social instead of ... rua=mailto:dmarc-reporting@hpc.social as it should have been (now fixed).

We were pretty close to going to full enforcement after running it in monitoring mode for a few weeks. The instance was only started in late November. If others are on a similar path with gradually adding enforcement to make sure things are okay, there may be other new servers still in the process of rolling this out. 

Thanks for your work in this area, whch can help catch these things.
